version: '2.1'
orbs:
  android: circleci/android@3.0.0
jobs:
  build:
    executor:
      name: android/android
      resource_class: medium
    docker:
      - image: cimg/android:2024.11-ndk
    steps:
      - checkout
      - run:
          name: Chmod Gradlew
          command: chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew dependencies
      - run:
          name: Build APK
          command: ./gradlew assembleDebug
      - run:
          name: Run Unit Tests
          command: ./gradlew test
      - store_artifacts:
          path: app/build/outputs/apk/debug/
      - store_test_results:
          path: app/build/test-results

workflows:
  version: 2
  build_and_test:
    jobs:
      - build